on:
  push:
    branches:
      - master
      - feat/*
    tags:
      - releases/v*.*.*

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-versions: [15.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-versions }}

      - run: npm install

      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - run: npm test
        if: runner.os != 'Linux'

  publish:
    if: startsWith(github.ref, 'refs/tags/releases')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
