name: ci/cd

env:
  NODE_VERSION: 15.x

on:
  push:
    branches:
      - master
      - feat/*
    tags:
      - releases/v*.*.*

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install llvm
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 10
          directory: ${{ runner.temp }}/llvm

      - run: llvm-cov --version

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci

      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - run: npm test
        if: runner.os != 'Linux'

  publish:
    if: startsWith(github.ref, 'refs/tags/releases')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci

      - name: Publishing to VSCode market place
        run: npm run deploy -p ${{ secrets.VSCE_PAT }}
