on:
  push:
    branches:
      - master
      - feat/*

  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-versions: [12.x, 14.x, 15.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-versions }}

      - run: npm install

      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - run: npm test
        if: runner.os != 'Linux'

      - name: Publish
        if: >
          success() && startsWith( github.ref, 'refs/tags/releases/')
          && ${{ matrix.os }} == 'ubuntu-latest'
          && ${{ matrix.node-versions }} == '15.x'
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
